apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mvp-test-component
  namespace: mvp-demo-dev-namespace-upyh-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:dae6248ea46b3819fe15479b7eb0099787654a1cc2602e4f8079db29a03f7ac5
        name: container-image
        resources: {}
status: {}
